license="MIT"

[[mixins]]
config="instant_leaf_decay.mixins.json"

[[mods]]
modId="instant_leaf_decay"
className="com.cukkoo.instantleafdecay.InstantLeafDecayMain"
version="${mod_version}"
displayName="Instant Leaf Decay"
logoFile="instant_leaf_decay.png"
credits="Cukkoo"
authors="Cukkoo"
description='''
Leaves decay instantly when trees are cut. No more floating leaf blobs!
'''

[[dependencies.instant_leaf_decay]]
modId="neoforge"
mandatory=true
versionRange="[26.2,)"
ordering="NONE"
side="BOTH"

[[dependencies.instant_leaf_decay]]
modId="minecraft"
mandatory=true
versionRange="[26.2,26.3)"
ordering="NONE"
side="BOTH"
